using System;
using System.Collections.Generic;
using Grasshopper.Kernel;
using Grasshopper.Kernel.Types;
using Rhino;
using Rhino.DocObjects;
using Rhino.Geometry;

namespace gh_sofistik.Structure
{
   // specialization of GH_Brep generated by axis components
   public class GH_AxisBrep : GH_Brep
   {
      public double EdgeThicknessLeft { get; set; } = 0.0;
      public double EdgeThicknessRight { get; set; } = 0.0;

      public GH_AxisBrep( Brep b )
         : base(b) { }

      public override string ToString()
      {
         return "Axis: " + base.ToString();
      }
   }

   // contains properties of a structural area
   public class GS_StructuralArea : GH_GeometricGoo<Brep>, IGH_PreviewData, IGH_BakeAwareData, IGS_StructuralElement
   {
      public int Id { get; set; } = 0;
      public int GroupId { get; set; } = 0;
      public int MaterialId { get; set; } = 0;
      public int ReinforcementId { get; set; } = 0;
      public double Thickness { get; set; } = 0.0;
      public Vector3d DirectionLocalX { get; set; } = new Vector3d();
      public bool FlipZ { get; set; } = false;
      public string Alignment { get; set; } = "CENT";
      public string MeshOptions { get; set; } = "AUTO";
      public double ElementSize { get; set; } = 0.0;
      public string UserText { get; set; } = string.Empty;

      public List<double> ThickessAtEdges { get; set; } = null; // optional list of thicknesses at boundary

      private LocalFrameVisualisation _localFrame = new LocalFrameVisualisation();
      private InfoPanel _infoPanel;

      public override BoundingBox Boundingbox
      {
         get { return Value.GetBoundingBox(true); }
      }

      public override string TypeDescription
      {
         get { return Value.ToString() + " with Structural Properties"; }
      }

      public override string TypeName
      {
         get { return "GS_StructuralArea"; }
      }

      public override string ToString()
      {
         return "Structural Area, Id = " + Id.ToString();
      }

      public override IGH_GeometricGoo DuplicateGeometry()
      {
         return new GS_StructuralArea()
         {
            Value = this.Value.DuplicateBrep(),
            Id = 0,
            GroupId = this.GroupId,
            MaterialId = this.MaterialId,
            ReinforcementId = this.ReinforcementId,
            Thickness = this.Thickness,
            DirectionLocalX = this.DirectionLocalX,
            FlipZ=this.FlipZ,
            Alignment = this.Alignment,
            MeshOptions = this.MeshOptions,
            ElementSize = this.ElementSize,
            UserText = this.UserText
         };
      }

      public override BoundingBox GetBoundingBox(Transform xform)
      {
         return xform.TransformBoundingBox(Value.GetBoundingBox(true));
      }

      public override bool CastTo<Q>(out Q target)
      {
         if(Value != null)
         {
            if(typeof(Q).IsAssignableFrom(typeof(GH_Brep)))
            {
               var gb = new GH_Brep(this.Value);
               target = (Q)(object)gb;
               return true;
            }
            else
            {
               throw new Exception("Unable to cast to type: " + typeof(Q).ToString());
            }
         }

         target = default(Q);
         return false;
      }

      public override IGH_GeometricGoo Morph(SpaceMorph xmorph)
      {
         var dup = this.DuplicateGeometry() as GS_StructuralArea;
         xmorph.Morph(dup.Value);

         return dup;
      }

      public override IGH_GeometricGoo Transform(Transform xform)
      {
         var dup = this.DuplicateGeometry() as GS_StructuralArea;

         dup.Value.Transform(xform);

         var localVX = dup.DirectionLocalX;
         localVX.Transform(xform);
         dup.DirectionLocalX = localVX;

         return dup;
      }

      public BoundingBox ClippingBox
      {
         get { return DrawUtil.GetClippingBoxLocalframe(Value.GetBoundingBox(false)); }
      }

      public void DrawViewportWires(GH_PreviewWireArgs args)
      {
         //ClippingBox
         //args.Pipeline.DrawBox(ClippingBox, System.Drawing.Color.Black);
         if (Value != null)
         {  
            System.Drawing.Color col = args.Color;
            if (!DrawUtil.CheckSelection(col))
               col = DrawUtil.DrawColorStructuralElements;
            else
            {
               drawLocalFrame(args.Pipeline);
               drawInfoPanel(args.Pipeline, args.Viewport);
            }

            args.Pipeline.DrawBrepWires(Value, col, -1);
         }
      }

      public void DrawViewportMeshes(GH_PreviewMeshArgs args)
      {
         if (Value != null)
         {  
            var col = args.Material.Diffuse;
            var areaStrcMaterial = args.Material;
            if (!DrawUtil.CheckSelection(col))
            {
               areaStrcMaterial = DrawUtil.DrawMaterialStructure;
            }
            
            args.Pipeline.DrawBrepShaded(Value, areaStrcMaterial);
         }
      }

      private void drawInfoPanel(Rhino.Display.DisplayPipeline pipeline, Rhino.Display.RhinoViewport viewport)
      {
         if (DrawUtil.DrawInfo)
         {
            if (_infoPanel == null)
            {
               _infoPanel = new InfoPanel();
               var amp = AreaMassProperties.Compute(Value);
               _infoPanel.Positions.Add(Value.ClosestPoint(amp.Centroid));
               if (Id != 0)
                  _infoPanel.Content.Add("Id: " + Id);
               if (GroupId != 0)
                  _infoPanel.Content.Add("Grp: " + GroupId);
            }
            _infoPanel.Draw(pipeline, viewport);
         }
      }

      private void drawLocalFrame(Rhino.Display.DisplayPipeline pipeline)
      {
         if (DrawUtil.ScaleFactorLocalFrame > 0.0001)
         {
            if (!_localFrame.IsValid)
            {
               updateLocalFrameTransforms();
            }
            _localFrame.Draw(pipeline);
         }
      }

      private void updateLocalFrameTransforms()
      {
         _localFrame.Transforms.Clear();

         Transform tScale = Rhino.Geometry.Transform.Scale(Point3d.Origin, DrawUtil.ScaleFactorLocalFrame);

         foreach (BrepFace bf in Value.Faces)
         {
            int n_seg_u = Math.Max(1, (int)(bf.IsoCurve(0, 0).GetLength() * DrawUtil.DensityFactorLocalFrame));
            int n_seg_v = Math.Max(1, (int)(bf.IsoCurve(1, 0).GetLength() * DrawUtil.DensityFactorLocalFrame));

            for (int i = 0; i <= n_seg_v; i++)
            {
               for (int j = 0; j <= n_seg_u; j++)
               {

                  double para_u = bf.Domain(0).ParameterAt((double)j / (double)n_seg_u);
                  double para_v = bf.Domain(1).ParameterAt((double)i / (double)n_seg_v);

                  if (DrawUtil.DensityFactorLocalFrame < 0.001)
                  {
                     para_u = bf.Domain(0).ParameterAt(0.5);
                     para_v = bf.Domain(1).ParameterAt(0.5);
                  }

                  Point3d ap = bf.PointAt(para_u, para_v);

                  Transform t = TransformUtils.GetGlobalTransformArea(ap, bf, DirectionLocalX);

                  if (FlipZ)
                     t = t * Rhino.Geometry.Transform.Rotation(Math.PI, Vector3d.XAxis, Point3d.Origin);

                  Transform tTranslate = Rhino.Geometry.Transform.Translation(new Vector3d(ap));

                  _localFrame.Transforms.Add(tTranslate * t * tScale);
               }
            }
         }
      }

      public bool BakeGeometry(RhinoDoc doc, ObjectAttributes baking_attributes, out Guid obj_guid)
      {
         if (Value != null)
         {
            var att = baking_attributes.Duplicate();

            att.SetUserString("SOF_OBJ_TYPE", "SAR");
            att.SetUserString("SOF_ID", Math.Max(0,Id).ToString());
            
            if(GroupId>0)
               att.SetUserString("SOF_GRP", GroupId.ToString());           
            if (MaterialId > 0)
               att.SetUserString("SOF_MNO", MaterialId.ToString());
            if (ReinforcementId > 0)
               att.SetUserString("SOF_MRF", ReinforcementId.ToString());
            
            att.SetUserString("SOF_T", Thickness.ToString());
            att.SetUserString("SOF_QREF", Alignment);

            if (MeshOptions == "AUTO")
               att.SetUserString("SOF_MCTL","0");
            else if(MeshOptions == "REGM")
               att.SetUserString("SOF_MCTL", "1");
            else if (MeshOptions == "SNGQ")
               att.SetUserString("SOF_MCTL", "2");
            else if (MeshOptions == "OFF")
               att.SetUserString("SOF_MCTL", "-1");

            if (ElementSize != 0.0)
               att.SetUserString("SOF_HMIN", ElementSize.ToString());

            if(DirectionLocalX.Length > 1.0e-6)
            {
               var dir_x = DirectionLocalX; dir_x.Unitize();

               att.SetUserString("SOF_DRX", dir_x.X.ToString("F6"));
               att.SetUserString("SOF_DRY", dir_x.Y.ToString("F6"));
               att.SetUserString("SOF_DRZ", dir_x.Z.ToString("F6"));
            }

            if (string.IsNullOrWhiteSpace(UserText) == false)
               att.SetUserString("SOF_USERTXT", UserText);

            obj_guid = doc.Objects.AddBrep(Value, att);
         }
         else
         {
            obj_guid = new Guid();
         }
         return true;
      }

   }


   // Structural Area node
   public class CreateStructuralArea : GH_Component
   {
      private System.Drawing.Bitmap _icon;

      public CreateStructuralArea()
         : base("Structural Area","Structural Area","Creates SOFiSTiK Structural Areas","SOFiSTiK", "Structure")
      { }

      protected override System.Drawing.Bitmap Icon
      {
         get
         {
            if (_icon == null)
               _icon = Util.GetBitmap(GetType().Assembly, "structural_area_24x24.png");
            return _icon;
         }
      }
      /*
      protected override string HtmlHelp_Source()
      {
         var urlTag = "GOTO:http://www.sofistik.de";
         var org = base.HtmlHelp_Source();
         return urlTag;
      }
      */
      protected override void RegisterInputParams(GH_InputParamManager pManager)
      {
         pManager.AddBrepParameter("Brep", "Brep", "Brep / Surface Geometry", GH_ParamAccess.list);
         pManager.AddIntegerParameter("Number", "Number", "Identifier of structural area", GH_ParamAccess.list, 0);
         pManager.AddIntegerParameter("Group", "Group", "Group numbers", GH_ParamAccess.list, 0);
         pManager.AddNumberParameter("Thickness", "Thickness", "Thickness of structural area", GH_ParamAccess.list, 0.0);
         pManager.AddIntegerParameter("Material", "Material", "Material number", GH_ParamAccess.list, 0);
         pManager.AddIntegerParameter("ReinforcementMaterial", "ReinfMat", "Reinforcement material number", GH_ParamAccess.list, 0);
         pManager.AddVectorParameter("Dir x", "Dir x", "Direction of local x-axis", GH_ParamAccess.list, new Vector3d());
         pManager.AddBooleanParameter("Flip z", "Flip z", "Flip Direction of local z-axis", GH_ParamAccess.list, false);
         pManager.AddTextParameter("Alignment", "Alignment", "Alignment of the shell element relative to the surface area (Centered = default, Above, Below)", GH_ParamAccess.list, "Centered");
         pManager.AddTextParameter("Mesh Options", "Mesh Options", "Mesh Options for the SOFiSTiK FE meshing (Automatic = default, Regular, Single Quad, Deactivate)", GH_ParamAccess.list, "Automatic");
         pManager.AddNumberParameter("Element Size", "Element Size", "Size of FE elements [m]", GH_ParamAccess.list, 0.0);
         pManager.AddTextParameter("User Text", "User Text", "Custom User Text to be passed to the SOFiSTiK input", GH_ParamAccess.list, string.Empty);
      }

      protected override void RegisterOutputParams(GH_OutputParamManager pManager)
      {
         pManager.AddGeometryParameter("Structural Area", "Sar", "SOFiSTiK Structural Area", GH_ParamAccess.list);
      }

      protected override void SolveInstance(IGH_DataAccess da)
      {
         var breps = da.GetDataList<GH_Brep>(0);
         var ids = da.GetDataList<int>(1);
         var groups = da.GetDataList<int>(2);
         var thicknss = da.GetDataList<double>(3);
         var materials = da.GetDataList<int>(4);
         var matreinfs = da.GetDataList<int>(5);
         var xdirs = da.GetDataList<Vector3d>(6);
         var zflip= da.GetDataList<bool>(7);
         var alignment = da.GetDataList<string>(8);
         var meshOptions = da.GetDataList<string>(9);
         var elementSize = da.GetDataList<double>(10);
         var userText = da.GetDataList<string>(11);

         var gh_structural_areas = new List<GS_StructuralArea>();

         for(int i=0; i<breps.Count; ++i)
         {
            var b = breps[i];

            if (!(b is null))
            {
               var ga = new GS_StructuralArea()
               {
                  Value = b.Value,
                  Id = ids.GetItemOrCountUp(i),
                  GroupId = groups.GetItemOrLast(i),
                  MaterialId = materials.GetItemOrLast(i),
                  ReinforcementId = matreinfs.GetItemOrLast(i),
                  Thickness = thicknss.GetItemOrLast(i),
                  DirectionLocalX = xdirs.GetItemOrLast(i),
                  FlipZ = zflip.GetItemOrLast(i),
                  Alignment = parseAlignmentString(alignment.GetItemOrLast(i)),
                  MeshOptions = parseMeshOptionsString(meshOptions.GetItemOrLast(i)),
                  ElementSize = elementSize.GetItemOrLast(i),
                  UserText = userText.GetItemOrLast(i)
               };

               // brep is of specific type generated along axis (with optional thickness information)
               if(b is GH_AxisBrep)
               {
                  var ba = b as GH_AxisBrep;

                  if(ba.EdgeThicknessLeft > 1.0E-4 || ba.EdgeThicknessRight > 1.0E-4)
                  {
                     var edgeThicknessList = new List<double> { ba.EdgeThicknessLeft, 0.0, ba.EdgeThicknessRight, 0.0 };
                     // reverse when AxisBrep was created with Brep.CreateFromLoft, keep original order when it was created with NurbsSurface.CreateRuledSurface
                     edgeThicknessList.Reverse();
                     ga.ThickessAtEdges = edgeThicknessList;
                  }
               }

               gh_structural_areas.Add(ga);
            }
         }

         da.SetDataList(0, gh_structural_areas);
      }

      private string parseAlignmentString(string s)
      {
         if(s is null)
         {
            this.AddRuntimeMessage(GH_RuntimeMessageLevel.Warning, "Alignment string is null. default value \"Centered\" will be used");
            return "CENT";
         }
            
         string slow = s.Trim().ToLower();

         string res = "CENT";
         if (slow.Equals("centered"))
            res = "CENT";
         else if (slow.Equals("above"))
            res = "ABOV";
         else if (slow.Equals("below"))
            res = "BELO";
         else
            this.AddRuntimeMessage(GH_RuntimeMessageLevel.Warning, "Alignment string is not valid. default value \"Centered\" will be used");

         return res;
      }

      private string parseMeshOptionsString(string s)
      {
         if (s is null)
         {
            this.AddRuntimeMessage(GH_RuntimeMessageLevel.Warning, "Mesh Options string is null. default value \"Automatic\" will be used");
            return "AUTO";
         }

         string slow = s.Trim().ToLower();

         string res = "AUTO";
         if(slow.Equals("automatic"))
            res = "AUTO";
         else if (slow.Equals("regular"))
            res = "REGM";
         else if (slow.Equals("single quad") || slow.Equals("singlequad"))
            res = "SNGQ";
         else if (slow.Equals("deactivate"))
            res = "OFF";
         else
            this.AddRuntimeMessage(GH_RuntimeMessageLevel.Warning, "Mesh Options string is not valid. default value \"Automatic\" will be used");

         return res;
      }

      public override Guid ComponentGuid
      {
         get { return new Guid("FC0973D1-0EC1-435A-ABD2-F6D9C7D3D7F3"); }
      }
   }

}